sudo: required

language: python

python:
  - "3.6"

env:
  global:
    - FLASK_ENV=testing
    - REDIS_HOST=localhost
    - REDIS_PORT=6379

services:
  - redis-server
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE benwaonlineauth_test;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON benwaonlineauth_test.* TO 'root'@'%';";

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pytest tests
