sudo: required

language: python

python:
  - "3.5"

env:
  - FLASK_CONFIG=test

services:
  - docker
  - mysql

before_install:
  - mysql -u root --password=""
  - mysql -e 'CREATE DATABASE benwaonlineauth_test;'
  - docker build -t goosechooser/benwaonline-auth:test .
  - docker run -d goosechooser/benwaonline-auth:test
  - docker ps -a

install:
  - pip install -r requirements.txt
  - pip install .

before_script:
  - echo -e "benwaonlineauth_test\nwait_timeout=28800" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart

script:
  - pytest tests

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push "$DOCKER_USERNAME"/benwaonline-auth;
    fi