sudo: required

language: python

python:
  - "3.6"

env:
  global:
    - FLASK_CONFIG=test
    - MEMCACHED_HOST=localhost
    - MEMCACHED_PORT=11211

services:
  - memcached
  - mysql
  - memcached

before_install:
  - mysql -u root -e 'CREATE DATABASE benwaonlineauth_test;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON benwaonlineauth_test.* TO 'root'@'%';";

install:
  - pip install -r requirements.txt
  - pip install -r requirements-testing.txt
  - pip install .

script:
  - pytest tests
