sudo: required

language: python

python:
  - "3.5"

env:
  - FLASK_CONFIG=test

services:
  - docker
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE benwaonlineauth_test;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON benwaonlineauth_test.* TO 'root'@'%';";

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest tests
