"""empty message

Revision ID: 0fbee2fad725
Revises:
Create Date: 2018-03-27 04:31:04.760117

"""
from alembic import op
from benwaonline_auth.models import GRANT_TYPES
import sqlalchemy_utils
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0fbee2fad725"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column(
            "grant_type",
            sqlalchemy_utils.types.choice.ChoiceType(GRANT_TYPES),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "grant_type")
    # ### end Alembic commands ###
